// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class voucher_table_seed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(voucher_table_seed));
        
        string IMigrationMetadata.Id
        {
            get { return "202510061731508_voucher_table_seed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
